# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
- repo: https://github.com/psf/break
  rev: 23.3.0  # 可以选择具体版本
  hooks:
    - id: break
      language_version: python3  # 使用 Python 3.8

